use std::{env,fs::{self,OpenOptions},io::Write,process::Command,thread,time::{Duration,SystemTime,UNIX_EPOCH}};
fn dir()->String{env::var("CORTEX_STATE").unwrap_or_else(|_|"/var/lib/cortex".into())}
fn esc(s:&str)->String{s.chars().flat_map(|c|match c{'\\'=>"\\\\".chars().collect::<Vec<_>>(),'"'=>"\\\"".chars().collect(), '\n'=>"\\n".chars().collect(), '\r'=>"\\r".chars().collect(), '\t'=>"\\t".chars().collect(), c if c.is_control()=>format!("\\u{:04x}",c as u32).chars().collect(), c=>vec![c]}).collect()}
fn rd(p:&str)->String{fs::read_to_string(p).unwrap_or_default()}
fn sh(cmd:&str)->(i32,String,String){match Command::new("/bin/sh").arg("-c").arg(cmd).output(){Ok(o)=>(o.status.code().unwrap_or(255),String::from_utf8_lossy(&o.stdout).chars().rev().take(4000).collect::<String>().chars().rev().collect(),String::from_utf8_lossy(&o.stderr).chars().rev().take(4000).collect::<String>().chars().rev().collect()),Err(e)=>(127,"".into(),e.to_string())}}
fn run(tool:&str,arg:&str)->(i32,String,String){match tool{"verify"=>sh(arg),"start"=>sh(&format!("/etc/init.d/{} start",arg)),"stop"=>sh(&format!("/etc/init.d/{} stop",arg)),"restart"=>sh(&format!("/etc/init.d/{} restart",arg)),"log"=>sh(&format!("tail -n 80 /var/log/{}",arg)),_ =>(126,"".into(),"denied".into())}}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
fn observe()->String{let (rc,ps,er)=sh("ps w");format!("{{\"t\":{},\"load\":\"{}\",\"mem\":\"{}\",\"mounts\":\"{}\",\"ps_rc\":{},\"ps\":\"{}\",\"ps_err\":\"{}\"}}",now(),esc(rd("/proc/loadavg").trim()),esc(&rd("/proc/meminfo").lines().take(5).collect::<Vec<_>>().join("\\n")),esc(&rd("/proc/mounts")),rc,esc(&ps),esc(&er))}
fn decide(state:&str)->Vec<(&'static str,String,&'static str)>{let mut v=vec![("verify","true".into(),"heartbeat")];if !state.contains("/sbin/watchdog"){v.push(("verify","echo watchdog-missing >/dev/console".into(),"diagnose"));}v.truncate(3);v}
fn append(path:&str,s:&str){if let Ok(mut f)=OpenOptions::new().create(true).append(true).open(path){let _=f.write_all(s.as_bytes());}}
fn main(){let s=dir();let _=fs::create_dir_all(&s);loop{let st=observe();let _=fs::write(format!("{}/state.json",s),&st);for (t,a,why) in decide(&st){let (rc,out,err)=run(t,&a);append(&format!("{}/journal.jsonl",s),&format!("{{\"t\":{},\"tool\":\"{}\",\"arg\":\"{}\",\"why\":\"{}\",\"rc\":{},\"out\":\"{}\",\"err\":\"{}\"}}\n",now(),t,esc(&a),why,rc,esc(&out),esc(&err)));}thread::sleep(Duration::from_secs(5));}}
