use serde::{Deserialize,Serialize};
use std::{collections::BTreeSet,env,fs::{self,OpenOptions},io::{Read,Write},os::unix::net::UnixStream,process::{Command,Stdio},thread,time::{Duration,SystemTime,UNIX_EPOCH}};
#[derive(Serialize)]struct State{t:u64,load:String,mem:Vec<String>,mounts:Vec<String>,ps_rc:i32,ps:String,ps_err:String}
#[derive(Serialize,Deserialize,Clone)]struct Action{tool:String,arg:String,why:String}
#[derive(Serialize,Deserialize)]struct Policy{allow_tools:BTreeSet<String>,allow_services:BTreeSet<String>,max_actions:usize,loop_secs:u64,require_verify:bool}
impl Default for Policy{fn default()->Self{Self{allow_tools:["verify","start","stop","restart","log"].into_iter().map(String::from).collect(),allow_services:["net","storage"].into_iter().map(String::from).collect(),max_actions:3,loop_secs:5,require_verify:false}}}
fn dir()->String{env::var("CORTEX_STATE").unwrap_or_else(|_|"/var/lib/cortex".into())}
fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
fn rd(p:&str)->String{fs::read_to_string(p).unwrap_or_default()}
fn sh(cmd:&str,stdin:Option<&str>)->(i32,String,String){let mut c=Command::new("/bin/sh");c.arg("-c").arg(cmd);if stdin.is_some(){c.stdin(Stdio::piped());}match c.stdout(Stdio::piped()).stderr(Stdio::piped()).spawn(){Ok(mut ch)=>{if let Some(s)=stdin{let _=ch.stdin.take().unwrap().write_all(s.as_bytes());}match ch.wait_with_output(){Ok(o)=>(o.status.code().unwrap_or(255),tail(&String::from_utf8_lossy(&o.stdout),4000),tail(&String::from_utf8_lossy(&o.stderr),4000)),Err(e)=>(127,"".into(),e.to_string())}},Err(e)=>(127,"".into(),e.to_string())}}
fn tail(s:&str,n:usize)->String{s.chars().rev().take(n).collect::<String>().chars().rev().collect()}
fn load_policy()->Policy{let p=env::var("CORTEX_POLICY").unwrap_or_else(|_|"/etc/cortex/policy.json".into());serde_json::from_str(&rd(&p)).unwrap_or_default()}
fn observe()->State{let (rc,ps,er)=sh("ps w",None);State{t:now(),load:rd("/proc/loadavg").trim().into(),mem:rd("/proc/meminfo").lines().take(8).map(String::from).collect(),mounts:rd("/proc/mounts").lines().map(String::from).collect(),ps_rc:rc,ps,ps_err:er}}
fn builtin(st:&State)->Vec<Action>{let mut v=vec![Action{tool:"verify".into(),arg:"true".into(),why:"heartbeat".into()}];if !st.ps.contains("/sbin/watchdog"){v.push(Action{tool:"verify".into(),arg:"echo watchdog-missing >/dev/console".into(),why:"diagnose".into()});}v}
fn model(st:&State)->Option<Vec<Action>>{let js=serde_json::to_string(st).ok()?;if let Ok(sock)=env::var("CORTEX_SOCK"){let mut s=UnixStream::connect(sock).ok()?;s.write_all(js.as_bytes()).ok()?;s.shutdown(std::net::Shutdown::Write).ok()?;let mut out=String::new();s.read_to_string(&mut out).ok()?;return serde_json::from_str(&out).ok();}if let Ok(cmd)=env::var("CORTEX_DECIDER"){let (rc,out,_) = sh(&cmd,Some(&js));if rc==0{return serde_json::from_str(&out).ok();}}None}
fn valid(a:&Action,p:&Policy)->bool{if !p.allow_tools.contains(&a.tool){return false}match a.tool.as_str(){"start"|"stop"|"restart"=>p.allow_services.contains(&a.arg),"log"=>!a.arg.contains('/')&&!a.arg.contains(".."),"verify"=>true,_=>false}}
fn exec(a:&Action)->(i32,String,String){match a.tool.as_str(){"verify"=>sh(&a.arg,None),"start"|"stop"|"restart"=>sh(&format!("/etc/init.d/{} {}",a.arg,a.tool),None),"log"=>sh(&format!("tail -n 80 /var/log/{}",a.arg),None),_=>(126,"".into(),"denied".into())}}
fn append(path:&str,v:&serde_json::Value){if let Ok(mut f)=OpenOptions::new().create(true).append(true).open(path){let _=writeln!(f,"{}",v);}}
fn step(s:&str){let p=load_policy();let st=observe();let state_json=serde_json::to_string_pretty(&st).unwrap();let _=fs::write(format!("{}/state.json",s),&state_json);let mut acts=model(&st).unwrap_or_else(||builtin(&st));acts.truncate(p.max_actions);for a in acts{let ok=valid(&a,&p);let (rc,out,err)=if ok{exec(&a)}else{(126,"".into(),"policy-denied".into())};append(&format!("{}/journal.jsonl",s),&serde_json::json!({"t":now(),"action":a,"allowed":ok,"rc":rc,"out":out,"err":err}));}}
fn main(){let s=dir();let _=fs::create_dir_all(&s);if env::var("CORTEX_ONCE").is_ok(){step(&s);return}loop{let p=load_policy();step(&s);thread::sleep(Duration::from_secs(p.loop_secs.max(1)));}}
