use serde::{Deserialize,Serialize};
use std::{collections::BTreeSet,env,fs::{self,OpenOptions},io::{Read,Write},os::unix::net::UnixStream,process::{Command,Stdio},thread,time::{Duration,Instant,SystemTime,UNIX_EPOCH}};
#[derive(Serialize)]struct State{t:u64,load:String,mem:Vec<String>,mounts:Vec<String>,ps_rc:i32,ps:String,ps_err:String}
#[derive(Serialize,Deserialize,Clone)]struct Action{tool:String,arg:String,why:String}
fn tools()->BTreeSet<String>{["verify","start","stop","restart","log"].into_iter().map(String::from).collect()}fn svcs()->BTreeSet<String>{["net","storage"].into_iter().map(String::from).collect()}fn prefixes()->Vec<String>{["true","echo ","test ","[ ","ps","cat /proc/","tail "].into_iter().map(String::from).collect()}fn maxa()->usize{3}fn loops()->u64{5}fn tout()->u64{8}fn maxarg()->usize{240}
#[derive(Serialize,Deserialize)]struct Policy{#[serde(default="tools")]allow_tools:BTreeSet<String>,#[serde(default="svcs")]allow_services:BTreeSet<String>,#[serde(default="prefixes")]allow_verify_prefixes:Vec<String>,#[serde(default="maxa")]max_actions:usize,#[serde(default="loops")]loop_secs:u64,#[serde(default="tout")]tool_timeout_secs:u64,#[serde(default="maxarg")]max_arg_len:usize,#[serde(default)]require_verify:bool}
impl Default for Policy{fn default()->Self{Self{allow_tools:tools(),allow_services:svcs(),allow_verify_prefixes:prefixes(),max_actions:maxa(),loop_secs:loops(),tool_timeout_secs:tout(),max_arg_len:maxarg(),require_verify:false}}}
fn dir()->String{env::var("CORTEX_STATE").unwrap_or_else(|_|"/var/lib/cortex".into())}fn now()->u64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}fn rd(p:&str)->String{fs::read_to_string(p).unwrap_or_default()}fn tail(s:&str,n:usize)->String{s.chars().rev().take(n).collect::<String>().chars().rev().collect()}
fn sh(cmd:&str,stdin:Option<&str>,timeout:u64)->(i32,String,String){let mut c=Command::new("/bin/sh");c.arg("-c").arg(cmd);if stdin.is_some(){c.stdin(Stdio::piped());}let mut ch=match c.stdout(Stdio::piped()).stderr(Stdio::piped()).spawn(){Ok(x)=>x,Err(e)=>return(127,"".into(),e.to_string())};if let Some(s)=stdin{let _=ch.stdin.take().map(|mut i|i.write_all(s.as_bytes()));}let start=Instant::now();loop{match ch.try_wait(){Ok(Some(_))=>break,Ok(None)=>{if start.elapsed()>Duration::from_secs(timeout.max(1)){let _=ch.kill();let _=ch.wait();return(124,"".into(),"timeout".into())}thread::sleep(Duration::from_millis(25));},Err(e)=>return(127,"".into(),e.to_string())}}match ch.wait_with_output(){Ok(o)=>(o.status.code().unwrap_or(255),tail(&String::from_utf8_lossy(&o.stdout),4000),tail(&String::from_utf8_lossy(&o.stderr),4000)),Err(e)=>(127,"".into(),e.to_string())}}
fn load_policy()->Policy{let p=env::var("CORTEX_POLICY").unwrap_or_else(|_|"/etc/cortex/policy.json".into());serde_json::from_str(&rd(&p)).unwrap_or_default()}
fn observe()->State{let (rc,ps,er)=sh("ps w",None,3);State{t:now(),load:rd("/proc/loadavg").trim().into(),mem:rd("/proc/meminfo").lines().take(8).map(String::from).collect(),mounts:rd("/proc/mounts").lines().map(String::from).collect(),ps_rc:rc,ps,ps_err:er}}
fn builtin(_:&State)->Vec<Action>{vec![Action{tool:"verify".into(),arg:"true".into(),why:"heartbeat".into()}]}
fn model(st:&State)->Option<Vec<Action>>{let js=serde_json::to_string(st).ok()?;if let Ok(sock)=env::var("CORTEX_SOCK"){let mut s=UnixStream::connect(sock).ok()?;s.write_all(js.as_bytes()).ok()?;s.shutdown(std::net::Shutdown::Write).ok()?;let mut out=String::new();s.read_to_string(&mut out).ok()?;return serde_json::from_str(&out).ok();}if let Ok(cmd)=env::var("CORTEX_DECIDER"){let (rc,out,_) = sh(&cmd,Some(&js),10);if rc==0{return serde_json::from_str(&out).ok();}}None}
fn safe_name(s:&str)->bool{!s.is_empty()&&s.len()<64&&s.chars().all(|c|c.is_ascii_alphanumeric()||c=='_'||c=='-'||c=='.')}fn shell_safe(s:&str)->bool{!s.chars().any(|c|matches!(c,';'|'&'|'|'|'`'|'$'|'(' | ')' | '<' | '>' | '\n' | '\r'))}
fn valid(a:&Action,p:&Policy)->bool{if !p.allow_tools.contains(&a.tool)||a.arg.len()>p.max_arg_len{return false}match a.tool.as_str(){"start"|"stop"|"restart"=>safe_name(&a.arg)&&p.allow_services.contains(&a.arg),"log"=>safe_name(&a.arg)&&!a.arg.contains('/')&&!a.arg.contains(".."),"verify"=>shell_safe(&a.arg)&&p.allow_verify_prefixes.iter().any(|x|a.arg==*x||a.arg.starts_with(x)),_=>false}}
fn exec(a:&Action,p:&Policy)->(i32,String,String){match a.tool.as_str(){"verify"=>sh(&a.arg,None,p.tool_timeout_secs),"start"|"stop"|"restart"=>sh(&format!("/etc/init.d/{} {}",a.arg,a.tool),None,p.tool_timeout_secs),"log"=>sh(&format!("tail -n 80 /var/log/{}",a.arg),None,p.tool_timeout_secs),_=>(126,"".into(),"denied".into())}}
fn append(path:&str,v:&serde_json::Value){if let Ok(mut f)=OpenOptions::new().create(true).append(true).open(path){let _=writeln!(f,"{}",v);}}
fn step(s:&str){let p=load_policy();let st=observe();let _=fs::write(format!("{}/state.json",s),serde_json::to_string_pretty(&st).unwrap());let mut acts=model(&st).unwrap_or_else(||builtin(&st));acts.truncate(p.max_actions);for a in acts{let ok=valid(&a,&p);let (rc,out,err)=if ok{exec(&a,&p)}else{(126,"".into(),"policy-denied".into())};append(&format!("{}/journal.jsonl",s),&serde_json::json!({"t":now(),"action":a,"allowed":ok,"rc":rc,"out":out,"err":err}));}}
fn main(){let s=dir();let _=fs::create_dir_all(&s);if env::var("CORTEX_ONCE").is_ok(){step(&s);return}loop{let p=load_policy();step(&s);thread::sleep(Duration::from_secs(p.loop_secs.max(1)));}}
